# Generated by Django 4.2 on 2023-04-25 23:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=50, verbose_name='Ability')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='Last name')),
                ('position', models.CharField(choices=[('0', 'Finances'), ('1', 'Admin'), ('2', 'Developer'), ('3', 'Other')], default='', max_length=20, verbose_name='Position')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulate')),
                ('life_sheet', ckeditor.fields.RichTextField()),
                ('ability', models.ManyToManyField(to='person.ability')),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'verbose_name_plural': 'Company employee',
                'ordering': ['last_name', 'name'],
            },
        ),
    ]
