# Generated by Django 4.2 on 2023-05-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre completo'),
        ),
    ]
