# Generated by Django 4.2 on 2023-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name')),
                ('short_name', models.CharField(default='', max_length=20, verbose_name='Short name')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulate')),
            ],
            options={
                'verbose_name_plural': 'Department',
                'ordering': ['-name'],
            },
        ),
    ]
