# Generated by Django 4.2 on 2023-05-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name_deparment'], 'verbose_name_plural': 'Department'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='name_deparment',
        ),
    ]
