# Generated by Django 4.2 on 2023-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='anulate',
        ),
    ]
