# Generated by Django 4.2 on 2023-06-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_anulate'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Anulate'),
        ),
    ]
